name: Publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to NPM"
        required: true
        default: "true"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
      - run: echo "Published ${{ steps.publish.outputs.name }}@${{ steps.publish.outputs.version }} to NPM"
