name: Release

on:
  workflow_call:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: "Bump Version & Create Tag"
        id: "bump-version"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
      - name: "Create Release"
        uses: "softprops/action-gh-release@v1"
        with:
          tag_name: ${{ steps.bump-version.outputs.newTag }}
          draft: false
          prerelease: false
          generate_release_notes: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish --provenance --access public
